export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY = 'GET_COUNTRY';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME';
export const FILTER_COUNTRIES_BY_ACTIVITIES = 'FILTER_COUNTRIES_BY_ACTIVITIES';

